# This is the configuration files for BOS
# Important fields to be edited here before running BOS are are
# 1. passphrase
# 2. BOOKIE_PROPOSER
# 3. BOOKIE_APPROVER
######################
# Witness endpoint
######################
# Ideally, the witness endpoint runs on localhost somewhere
node: ws://localhost:8090
# How to use an external witness endpoint
#node: wss://hercules.peerplays.download/api


######################
# PeerPlays network
######################
# This allows you to specify which version of bookiesport to take
# If you connect to Alice (PeerPlays) and try to use network Baxter
# (PeerPlays testnetwork), an exception will be raised!
# To clarify
#
#   * alice: PeerPlays main blockchain
#   * baxter: PeerPlays public testnet blockchain
#   * charlie: PBSA internal development blockchain
#
network: alice
connection:
    use: alice

    alice:
        node:
              # - wss://pma.blockveritas.co/ws
              # - wss://api.eifos.org
            - ws://localhost:8090
              # - wss://ppyapi.spacemx.tech
        nobroadcast: False
        num_entries: 1

    #testnet-public:
    #    node:
    #        - wss://x.x.x/api
    #    nobroadcast: False
    #    num_entries: 1

    devnet:
        node:
            - wss://devnet.peerplays.download/api
        nobroadcast: False
        num_entries: 1

    alphanet:
        node:
            - wss://alphanet.peerplays.download/api
        nobroadcast: False
        num_entries: 1



######################
## Redis configuration
######################
# This allows you to optionally use a redis database that is not on
# localhost.
redis_host:
redis_port:
redis_password:
redis_db:

#####################
# Safe mode (if True)
#####################
# If this is set to true, the entire software suite will behave as
# usualy but not send any transactions to the backend node.
nobroadcast: False

###################
# Wallet passphrase
###################
# Once you added your active private key into local python-peerplays
# database, you have picked a wallet passphrase. Please provide this
# here to allow bos-auto to spin up automatically on powerup.
passphrase: <Your server wallet passphrase here>

##################
# Data Proxy IP Whitelist
##################
# This option allows to define who is allowed to access the web endpoint
# to send messages to. This is a list of IP or hostnames that are
# resovled at the launch time. DNS changes during run time will not
# propagate!
#
#   * 0.0.0.0 - will allow anyone to send messages
#   * dataproxy.example.com - IP address resolved at startup time.
#
api_whitelist:
        #  - 0.0.0.0
 - 142.93.5.5
 - 193.31.27.181
 - localhost

##################
# Proposer account
##################
# Please provide the account name of the witnesse that is *proposing*
# new proposals. This **must** be an active witness account, otherwise,
# other witnesses will not approve it.
#
# Technically, this needs to be the account name of your witness
BOOKIE_PROPOSER: <Your Peerplays account name here>

##################
# Approver account
##################
# Provide the account name that approves proposals for witnesses. This
# must be your active witness-account, otherwise it will not affect
# consensus of any given proposal for witnesses.
#
# Technically, this needs to be the account name of your witness
BOOKIE_APPROVER: <Your Peerplays account name here>

####################################
# Logging setup
####################################
logging:
    level: INFO
    console: True
    file:

    # Default mail destination on errors
    # if your server is properly set up, you will receive email
    # notifications on errors to this email address
    mailto:

    # Telegram
    # Notifications via telgram
    #
    # Please read
    #
    #   https://github.com/sashgorokhov/python-telegram-handler
    #
    # for setting up a telegram notification bot.
    # python3 -m telegram_handler "${telegram_token}"
    telegram_token:
    telegram_chatid:
    
###################################
# Incidents handling configuration
####################################
scheduler:
# scheduler runs every x seconds
# scheduler runs every x seconds 
        interval: 60 
expirations: 
# event can't be opened due to leadtime_max in bookiesports yet 
        EventCannotOpenException: 43200 
# waiting for more incidents before executing (dynamic betting markets) 
        PostPoneIncidentException: 3600 
# retry unhandled exception once after this time, randomization is added 
        UnhandledException: 300 

